### ISSUE TITLE
Compute Owasp Benchmark score is broken

### ISSUE THREAD

**Issue by Qwarctick** [DataDog/datadog-static-analyzer#351]
**Describe the bug**

In the documentation https://github.com/DataDog/datadog-static-analyzer/blob/main/doc/owasp-benchmark.md, the computation of the owasp score is broken:

``` bash
# ./createScorecards.sh
[INFO] BuildTimeEventSpy is registered.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------< org.owasp:benchmark >-------------------------
[INFO] Building OWASP Benchmark for Java 1.2
[INFO] --------------------------------[ war ]---------------------------------
[INFO]
[INFO] --- benchmarkutils-maven-plugin:1.3:create-scorecard (default-cli) @ benchmark ---
Usage: -cf /PATH/TO/scoringconfigfile.yaml or -cr scoringconfigfile.yaml (where file is a resource)
Analyzing results from Benchmark_1.2-DatadogSast.sarif
Error!!: actual results were null for file: results/Benchmark_1.2-DatadogSast.sarif
```

**To Reproduce**

Follow steps in the doc https://github.com/DataDog/datadog-static-analyzer/blob/main/doc/owasp-benchmark.md

**Version:**
 - OS: Ubuntu 22.04
 - BenchmarkJava : version from master github.
 - rustc stable-x86_64-unknown-linux-gnu (default) 1.76.0
 - openjdk version "19.0.2"

**Comment by juli1** [comment]
Thank you for your bug report! Can you please try using the branch `juli1/add-datadog-support` of `BenchmarkUtils`? I may have forgotten this step!

**Comment by Qwarctick** [comment]
Thanks for the fast reply :) It works great with the branch information.

I confirm that this step can be added to the doc.
