### ISSUE TITLE
cargo test fails in a clean cloned repo

### ISSUE THREAD

**Issue by robertohuertasm** [DataDog/datadog-static-analyzer#7]
**Describe the bug**
cargo test fails most of the time in some of the tests. Note that the behavior is not consistent. Sometime it passes all the tests.

**To Reproduce**
1. Clean the repo
2. cargo build
3. cargo test

**Expected behavior**
All the tests to pass

**Screenshots**
<img width="1119" alt="image" src="https://github.com/DataDog/datadog-static-analyzer/assets/696981/f054f96d-2206-487f-bb42-b8ca59daa2c7">

**Desktop (please complete the following information):**
 - OS: MacOs Ventura 13.4.1

**Comment by robertohuertasm** [comment]
I've tried updating the javascript timeout to 10s but still the same issue. If I run the `invalid_javascript` test alone, it works. So I suspect it may be a problem of some shared resource. I've not looked into more details yet.

**Comment by robertohuertasm** [comment]
I've tested this in WSL2 and I can't reproduce it there, but it's pretty consistent in my M1.

**Comment by juli1** [comment]
@robertohuertasm can you please try on the latest `main`? The issue is related to [this change](https://github.com/DataDog/datadog-static-analyzer/pull/13) and should be fixed now.

**Comment by robertohuertasm** [comment]
Hi @juli1, fixed! 🚀
